os: linux
dist: xenial
language: perl
perl:
  - "5.26"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y " #newick tools
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."

before_script:
  - "make install_auto"

script:
  - "make test"

notifications:
  email:
    on_failure: always
