os: linux
dist: xenial
language: perl
perl:
  - "5.30"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y libdb-dev"
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."
  - "git clone git://github.com/tjunier/newick_utils.git && cd newick_utils && ./configure && make && sudo make install"

script:
  - "make test"

notifications:
  email:
    on_failure: always
